apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cnf-certifications.redhat.com/v1alpha1",
          "kind": "CnfCertificationSuiteRun",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "tnf-op",
              "app.kubernetes.io/instance": "cnfcertificationsuiterun-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "cnfcertificationsuiterun",
              "app.kubernetes.io/part-of": "tnf-op"
            },
            "name": "cnfcertificationsuiterun-sample",
            "namespace": "cnf-certsuite-operator"
          },
          "spec": {
            "configMapName": "cnf-certsuite-config",
            "labelsFilter": "observability",
            "logLevel": "info",
            "preflightSecretName": "cnf-certsuite-preflight-dockerconfig",
            "timeout": "2h"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-01-25T07:40:11Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: tnf-op.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CnfCertificationSuiteReport is the Schema for the cnfcertificationsuitereports
        API
      displayName: Cnf Certification Suite Report
      kind: CnfCertificationSuiteReport
      name: cnfcertificationsuitereports.cnf-certifications.redhat.com
      version: v1alpha1
    - description: CnfCertificationSuiteRun is the Schema for the cnfcertificationsuiteruns
        API
      displayName: Cnf Certification Suite Run
      kind: CnfCertificationSuiteRun
      name: cnfcertificationsuiteruns.cnf-certifications.redhat.com
      version: v1alpha1
  description: CNF Certification Suite Operator
  displayName: CNF Op
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: cnf-certsuite-cluster-access
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cnf-certsuite-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: tnf-op
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: tnf-op
          control-plane: controller-manager
        name: cnf-certsuite-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: SIDECAR_APP_IMG
                  value: quay.io/testnetworkfunction/cnf-certsuite-operator-sidecar:v0.0.1
                image: quay.io/testnetworkfunction/cnf-certsuite-operator:v0.0.1
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: cnf-certsuite-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuitereports
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuitereports/finalizers
          verbs:
          - update
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuitereports/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuiteruns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuiteruns/finalizers
          verbs:
          - update
        - apiGroups:
          - cnf-certifications.redhat.com
          resources:
          - cnfcertificationsuiteruns/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: cnf-certsuite-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - redhat
  - certification
  - cnf
  - openshift
  links:
  - name: Tnf Op
    url: https://tnf-op.domain
  maturity: alpha
  provider:
    name: RedHat
  version: 0.0.1
