---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cnf-certifications-redhat-com-v1alpha1-cnfcertificationsuiterun
  failurePolicy: Fail
  name: vcnfcertificationsuiterun.kb.io
  rules:
  - apiGroups:
    - cnf-certifications.redhat.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cnfcertificationsuiteruns
  sideEffects: None
