---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: cnf-certification-operator
rules:
- apiGroups:
  - ""
  resources:
  - configMaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnf-certifications.redhat.com
  resources:
  - cnfcertificationsuiteruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnf-certifications.redhat.com
  resources:
  - cnfcertificationsuiteruns/finalizers
  verbs:
  - update
- apiGroups:
  - cnf-certifications.redhat.com
  resources:
  - cnfcertificationsuiteruns/status
  verbs:
  - get
  - patch
  - update
