apiVersion: cnf-certifications.redhat.com/v1alpha1
kind: CnfCertificationSuiteRun
metadata:
  labels:
    app.kubernetes.io/name: cnfcertificationsuiterun
    app.kubernetes.io/instance: cnfcertificationsuiterun-sample
    app.kubernetes.io/part-of: cnf-certsuite-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cnf-certsuite-operator
  name: cnfcertificationsuiterun-sample
  namespace: cnf-certsuite-operator
spec:
  # TODO(user): Add fields here
  labelsFilter: "observability"
  logLevel: "info"
  timeout: "2h"

  configMapName: "cnf-certsuite-config"
  preflightSecretName : "cnf-certsuite-preflight-dockerconfig"
  enableDataCollection: false
  showAllResultsLogs: false
  showCompliantResourcesAlways: false